### ISSUE TITLE
Readme is a bit sparse

### ISSUE THREAD

**Issue by ghost** [iassael/torch-policy-gradient#1]
A thorough list of prerequisites and instructions to run this would be appreciated. I'm running ubunto 16.04 with Python 2.7, I've installed the prerequisites listed and have a working Torch7 installation. I have iPython and iTorch installed. When I run itorch notebook, select the dpg.ipynb file and run it, I just get a syntax error on the first line.

 File "<ipython-input-1-7871ce6dfd18>", line 1
    if itorch then
                 ^
SyntaxError: invalid syntax

Obviously I'm missing something basic, just not sure what.

**Comment by iassael** [comment]
@BrianWestlake it seems that the python kernel is being executed instead of torch in the notebook. Did you try updating and then force the torch kernel to load by opening the notebook and then Menu -> Kernel -> Change Kernel -> Torch?

Otherwise, you can go to File -> Download As ->  Lua, which should run but you would miss the visualisations.

**Comment by ghost** [comment]
Thanks, switching kernels sorted it out
